backend:
  name: github
  repo: RabeeLuqmann/rabeeluqmann.github.io
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "index"
        label: "Home Page"
        file: "index.html"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "body", label: "Content", widget: "markdown" }
